create table tb_jedis (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_missions (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, jedi_id int8, primary key (id));
alter table if exists tb_missions add constraint FKnr24l7g8sede0xeb75wspu3qa foreign key (jedi_id) references tb_jedis;
